name: Bug report
description: File a bug report
title: "[Bug] "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Please note that I do not provide support for clients other than Forge.
        I will not fix compatibility issues with other clients.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What did not work? What did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: modVersion
    attributes:
      label: Smixer Version
      multiple: false
      options:
        - 1.0.0
    validations:
      required: true
  - type: textarea
    id: otherMods
    attributes:
      label: Other Installed Mods
      description: |
        Please list the names and versions of the other mods you have installed.
      placeholder: |
        Optifine M5
        NEU
        Skytils
  - type: input
    id: operatingSystem
    attributes:
      label: Operating System
      placeholder: |
        Windows 11
        Windows 10
    validations:
      required: true
  - type: textarea
    id: crashReport
    attributes:
      label: Crash Report
      description: |
        If your game crashed, please paste the crash report below.
        If your crash report has a name starting with `hs_err_pid`, **do not post it here!** It contains your login credentials. Message us on Discord instead.
  - type: markdown
    attributes:
      value: |
        **Attachments**
        If you have attachments like screenshots or videos, please upload them in a comment after creating the bug report.